version: "3.8"
services:
  app:
    container_name: back
    build: .
    command: sh -c "make migrate && ./store"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=./configs/config.yaml
  db:
    container_name: db
    restart: always
    image: "postgres:15.4-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"