version: "3.8"
services:
  app:
    container_name: backend
    build: app
    command: sh -c "sleep 10 && make migrate && ./store"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=./configs/config.yaml
  db:
    container_name: postgres
    restart: always
    image: "postgres:15.4-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"
  node:
    container_name: node
    build: public
    ports:
      - "3000:3000"
    command: http-server -p 3000